spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ludoteca_nombreAlumno #(Server local)
    #url: jdbc:mysql://172.16.1.64:3306/ludoteca_nombreAlumno (Server UTN)

    username: root #(Server Local)
    #username: bdd1 (Server UTN)

    password: 1234 #(Server Local)
    #password: bdd1 (Server UTN)

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect